{% set name = "tilupy" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tilupy-{{ version }}.tar.gz
  sha256: 110182377607067b93a12b44618f1779741585a979dedbddcb662a81da4ab77b

build:
  entry_points:
    - tilupy_plot = tilupy.cmd:_tilupy_plot
    - tilupy_to_raster = tilupy.cmd:_tilupy_to_raster
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0.0
    - wheel
    - pip
  run:
    - python >=3.8
    - seaborn
    - requests
    - scipy

test:
  imports:
    - tilupy
  commands:
    - pip check
    - tilupy_plot --help
    - tilupy_to_raster --help
  requires:
    - pip

about:
  home: https://github.com/marcperuz/tilupy
  summary: Thin-layer models unified processing tool
  license: CECILL-C
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcperuz
