{% set name = "tilupy" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tilupy-{{ version }}.tar.gz
  sha256: ccefb1f16f4e6d7d58a391af454ba396cf8a5111d305185a1da6cac20dc508e1

build:
  entry_points:
    - tilupy_plot = tilupy.cmd:_tilupy_plot
    - tilupy_to_raster = tilupy.cmd:_tilupy_to_raster
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - seaborn
    - requests
    - scipy

test:
  imports:
    - tilupy
  commands:
    - pip check
    - tilupy_plot --help
    - tilupy_to_raster --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/marcperuz/tilupy
  summary: Thin-layer models unified processing tool
  license: CECILL-C
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcperuz
